import { Document, Page, Text, View, StyleSheet, Image, Svg, Path } from "@react-pdf/renderer";
import type { ScanHistoryEntry } from "@/lib/store/scan-history-store";

const COLORS = {
  bg: "#0d0d0f",
  panel: "#16171a",
  border: "#2a2b30",
  text: "#f5f5f6",
  muted: "#9ca3af",
  blue: "#00a3d9",
  purple: "#5a3fe0",
  success: "#0aa876",
  warning: "#c98a00",
  danger: "#d43a56",
};

const styles = StyleSheet.create({
  page: { backgroundColor: "#ffffff", color: "#111318", padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  coverPage: { backgroundColor: COLORS.bg, color: COLORS.text, padding: 48, fontFamily: "Helvetica" },
  coverTop: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 40 },
  logo: { width: 32, height: 32, borderRadius: 6 },
  brand: { fontSize: 14, fontWeight: 700, color: COLORS.text },
  coverTitle: { fontSize: 30, fontWeight: 700, marginTop: 160, color: COLORS.text },
  coverSubtitle: { fontSize: 12, color: COLORS.muted, marginTop: 10 },
  coverMeta: { position: "absolute", bottom: 48, left: 48, right: 48, flexDirection: "row", justifyContent: "space-between", fontSize: 9, color: COLORS.muted },
  sectionTitle: { fontSize: 16, fontWeight: 700, marginBottom: 10, color: "#111318" },
  paragraph: { fontSize: 10, lineHeight: 1.6, color: "#333", marginBottom: 10 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e5e5e5", paddingVertical: 6 },
  tableHeaderRow: { flexDirection: "row", borderBottomWidth: 1.5, borderBottomColor: "#111318", paddingVertical: 6 },
  th: { fontSize: 8, fontWeight: 700, color: "#111318", textTransform: "uppercase" },
  td: { fontSize: 9, color: "#333" },
  colTarget: { width: "35%" },
  colType: { width: "20%" },
  colScore: { width: "15%" },
  colLevel: { width: "15%" },
  colDate: { width: "15%" },
  badge: { fontSize: 8, fontWeight: 700, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 3, color: "#fff", alignSelf: "flex-start" },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#999", flexDirection: "row", justifyContent: "space-between" },
  findingCard: { marginBottom: 8, padding: 8, borderWidth: 1, borderColor: "#e5e5e5", borderRadius: 4 },
  findingTitle: { fontSize: 10, fontWeight: 700, color: "#111318" },
  findingDesc: { fontSize: 9, color: "#555", marginTop: 2 },
});

function levelColor(level: string) {
  switch (level) {
    case "critical":
    case "high":
      return COLORS.danger;
    case "medium":
      return COLORS.warning;
    case "low":
      return COLORS.blue;
    default:
      return COLORS.success;
  }
}

function ShieldMark() {
  return (
    <Svg width={32} height={32} viewBox="0 0 24 24">
      <Path d="M12 2l8 3v6c0 5-3.5 8.5-8 11-4.5-2.5-8-6-8-11V5l8-3z" fill="#00c2ff" />
    </Svg>
  );
}

export interface ReportInput {
  companyName: string;
  companyLogo: string | null;
  generatedAt: string;
  entries: ScanHistoryEntry[];
}

export function SecurityReportDocument({ companyName, companyLogo, generatedAt, entries }: ReportInput) {
  const avgScore = entries.length ? Math.round(entries.reduce((s, e) => s + e.score, 0) / entries.length) : 0;
  const critical = entries.filter((e) => e.level === "critical").length;
  const high = entries.filter((e) => e.level === "high").length;

  return (
    <Document title={`${companyName} Security Assessment Report`} author="SentinelX">
      <Page size="A4" style={styles.coverPage}>
        <View style={styles.coverTop}>
          {/* eslint-disable-next-line jsx-a11y/alt-text -- react-pdf's Image (PDF renderer) has no alt prop */}
          {companyLogo ? <Image src={companyLogo} style={styles.logo} /> : <ShieldMark />}
          <Text style={styles.brand}>{companyName}</Text>
        </View>
        <Text style={styles.coverTitle}>Security Assessment Report</Text>
        <Text style={styles.coverSubtitle}>Generated by SentinelX — AI Cybersecurity Intelligence Platform</Text>
        <View style={styles.coverMeta}>
          <Text>{new Date(generatedAt).toLocaleString()}</Text>
          <Text>{entries.length} scan(s) included</Text>
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.paragraph}>
          This report summarizes {entries.length} security scan{entries.length === 1 ? "" : "s"} performed with SentinelX, covering websites, IP
          addresses, domains, and breach exposure checks. The average composite risk score across all included scans was {avgScore} out of 100
          (higher indicates greater risk). {critical > 0 || high > 0
            ? `${critical + high} scan(s) surfaced critical or high-severity findings that require prompt attention.`
            : "No scans surfaced critical or high-severity findings at the time of assessment."}
        </Text>

        <Text style={styles.sectionTitle}>Scan Overview</Text>
        <View style={styles.tableHeaderRow}>
          <Text style={[styles.th, styles.colTarget]}>Target</Text>
          <Text style={[styles.th, styles.colType]}>Type</Text>
          <Text style={[styles.th, styles.colScore]}>Risk Score</Text>
          <Text style={[styles.th, styles.colLevel]}>Level</Text>
          <Text style={[styles.th, styles.colDate]}>Date</Text>
        </View>
        {entries.map((e) => (
          <View key={e.id} style={styles.tableRow}>
            <Text style={[styles.td, styles.colTarget]}>{e.target}</Text>
            <Text style={[styles.td, styles.colType]}>{e.type}</Text>
            <Text style={[styles.td, styles.colScore]}>{e.score}</Text>
            <View style={styles.colLevel}>
              <Text style={[styles.badge, { backgroundColor: levelColor(e.level) }]}>{e.level.toUpperCase()}</Text>
            </View>
            <Text style={[styles.td, styles.colDate]}>{new Date(e.timestamp).toLocaleDateString()}</Text>
          </View>
        ))}

        <Text style={{ ...styles.sectionTitle, marginTop: 24 }}>Recommendations</Text>
        <Text style={styles.paragraph}>
          1. Remediate all critical and high-severity findings within 72 hours.{"\n"}
          2. Re-run affected scans after remediation to confirm resolution.{"\n"}
          3. Enable continuous monitoring (Dark Web Monitor, SSL expiry) for all in-scope assets.{"\n"}
          4. Review this report with stakeholders and track remediation to closure.
        </Text>

        <View style={styles.footer} fixed>
          <Text>{companyName} — Confidential</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Technical Appendix — Scan Summaries</Text>
        {entries.map((e) => (
          <View key={e.id} style={styles.findingCard}>
            <Text style={styles.findingTitle}>
              {e.target} ({e.type})
            </Text>
            <Text style={styles.findingDesc}>
              Risk score {e.score}/100 · {e.level.toUpperCase()} · {e.summary}
            </Text>
            <Text style={styles.findingDesc}>Scanned {new Date(e.timestamp).toLocaleString()}</Text>
          </View>
        ))}
        <View style={styles.footer} fixed>
          <Text>{companyName} — Confidential</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
